- name: Copy Docker Compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml

- name: Log in to GitLab Container Registry
  docker_login:
    registry: registry.gitlab.com
    username: "{{ gitlab_username }}"
    password: "{{ gitlab_password }}"

- name: Run docker compose up
  docker_compose:
    project_src: /home/{{ ansible_user }}/
    state: present
    recreate: true
